# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894ceb17ab2e6a5e622bd480ba1a2799453b6e87665ea9d1d4fca57b6507ac071fd0bec30c77d85c86c1e84843f45eccdd5ba2871b52279e8449e1458aa3d6cc

test:
  secret_key_base: ad0b57b504472c2f798539e60aa782792d7c0d4d5fe8b8bbdffb0c2e283e92a5f87f43b069307901588df3d9f34e5308534332fcac194d16f71d50bf9b766698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
